<<<<<<< HEAD
[build]
  base    = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[[redirects]]
  from    = "/*"
  to      = "/index.html"
=======
[build]
  base    = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[[redirects]]
  from    = "/*"
  to      = "/index.html"
>>>>>>> origin
  status  = 200